image: phpunit/phpunit:5.0.3
pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update
            - apt-get -qq install git-ftp
            - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD $FTP_SERVER